# Generated by Django 2.2.6 on 2020-06-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteinputmodel',
            old_name='opp_url',
            new_name='cloudOpportunityURL',
        ),
        migrations.RenameField(
            model_name='quoteinputmodel',
            old_name='managed_services',
            new_name='hasTheEnterpriseCloudManagedServicesBeenExcludedByaCDSRep',
        ),
        migrations.RenameField(
            model_name='quoteinputmodel',
            old_name='local_Currency',
            new_name='localCurrency',
        ),
        migrations.RenameField(
            model_name='quoteinputmodel',
            old_name='managed_services_rep',
            new_name='managedServicesRep',
        ),
        migrations.RenameField(
            model_name='quoteinputmodel',
            old_name='quote_name',
            new_name='quoteName',
        ),
        migrations.RenameField(
            model_name='quoteinputmodel',
            old_name='Opportunity_ID',
            new_name='salesForceCloudOpportunityID',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='Leading_Product',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='lead_name',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='penalties',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='term_type',
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='CDMCostRateUSDhr',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='CDSMonthlyHours',
            field=models.IntegerField(help_text='15hrs is the minimum, approvals required for less', null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='CPSCostRateUSDhr',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='CPSMonthlyHours',
            field=models.IntegerField(help_text='30hrs is the minimum, approvals required for less', null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='DRPlanningLaborCostRateUSDhr',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='annualPriceAdjustment',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='annualUsersIncreaseOfTotal',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='changeRequestOrAddOnOnly',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='cloudDeskSpecialist',
            field=models.CharField(choices=[('Arlene Branham', 'Arlene Branham'), ('John Smith', 'John Smith'), ('Sharron Harman', 'Sharron Harman'), ('Harry Anderson', 'Harry Anderson')], max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='cloudMargin',
            field=models.FloatField(default=47.0),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='cloudOpportunityType',
            field=models.CharField(choices=[('Cloud Subscription', 'Cloud Subscription'), ('Cloud Perpetual', 'Cloud Perpetual'), ('SaaS', 'SaaS')], max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='cloudTermMonths',
            field=models.IntegerField(default=36),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='customerName',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='endOfFirstYearUsersOfTotal',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='ifCRAddOnGCPAlreadyProvisionedNetAppCVO',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='inRegionNAEMEAPersonnelOnly',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='incrementalECMSHeadcountRequiredAsPartOfTheECMS',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='leadingProduct',
            field=models.CharField(choices=[('OpenText ContentSuite', 'OpenText ContentSuite'), ('OpenText Experience Suite', 'OpenText Experience Suite'), ('OpenText Process Suite', 'OpenText Process Suite'), ('OpenText Information Exchange Suite', 'OpenText Information Exchange Suite'), ('OpenText Discovery Suite', 'OpenText Discovery Suite'), ('OpenText Suite for SAP', 'OpenText Suite for SAP'), ('OpenText Suite for Oracle', 'OpenText Suite for Oracle'), ('OpenText Suite for Microsoft', 'OpenText Suite for Microsoft'), ('OpenText Appworks', 'OpenText Appworks'), ('OpenText Cloud', 'OpenText Cloud')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='manualInstallationCost',
            field=models.FloatField(help_text='If populated, this overrides the automation of installation costs within the VM tab. Use for Daas', max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='nonStandardTermsOrPenalties',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='removeAmortized10kUSDFee100Margin',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='requireTimelineBasedChanges',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='totalUsersOverTerm',
            field=models.IntegerField(null=True),
        ),
    ]
