# Generated by Django 2.2.6 on 2020-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0003_hostingprovidermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostingProviderModel',
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='backupNonProductionEnvironments',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='customerRequestedApplicationAvailabilitySLA',
            field=models.FloatField(choices=[(99, 99), (99.5, 99.5), (99.9, 99.9)], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='customerRequestedPrimaryDC',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='customerRequestedRTORPOSLA',
            field=models.CharField(choices=[('RTO 7days / RPO 24hrs', 'RTO 7days / RPO 24hrs'), ('RTO 8hrs / RPO 8hrs', 'RTO 8hrs / RPO 8hrs'), ('RTO 4hrs / RPO 4hrs', 'RTO 4hrs / RPO 4hrs')], max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='customerRequestedSecondaryOrMoreDCs',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='disasterRecovery',
            field=models.CharField(choices=[('--------------', '--------------'), ('OT - Standard', 'OT - Standard'), ('OT - EDR via Twin DCs', 'OT - EDR via Twin DCs'), ('OT DC with GCP for EDR', 'OT DC with GCP for EDR'), ('GCP Single-region Multi-Zone DR', 'GCP Single-region Multi-Zone DR'), ('GCP Multi-region EDR (geographic separation)', 'GCP Multi-region EDR (geographic separation)'), ('Azure Single-region Multi-Zone DR', 'Azure Single-region Multi-Zone DR'), ('Azure Multi-region EDR (geographic separation)', 'Azure Multi-region EDR (geographic separation)'), ('AWS Single-region Multi-Zone DR', 'AWS Single-region Multi-Zone DR'), ('AWS Multi-region EDR (geographic separation)', 'AWS Multi-region EDR (geographic separation)')], max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='encryptionAtRest',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='enhancedDRPlanningHrsPcm',
            field=models.FloatField(choices=[('--------------', '--------------'), (16.67, 16.67)], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='explanationOfMultipleActiveRegions',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='hostingModel',
            field=models.CharField(choices=[('OpenText', 'OpenText'), ('OpenText Australia', 'OpenText Australia'), ('OpenText Canada', 'OpenText Canada'), ('GCP', 'GCP'), ('Azure', 'Azure'), ('AWS', 'AWS'), ('Customer', 'Customer')], max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='isThisADaaSBasedCloudService',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='location',
            field=models.CharField(blank=True, choices=[('--------------', '--------------'), ('OT - US Twins', 'OT - US Twins'), ('OT - EMEA Twins', 'OT - EMEA Twins'), ('OT - Japan Twins', 'OT - Japan Twins'), ('OT - Sydney', 'OT - Sydney'), ('OT - Toronto', 'OT - Toronto'), ('GCP - US', 'GCP - US'), ('GCP - NA-NE', 'GCP - NA-NE'), ('GCP - Europe', 'GCP - Europe'), ('GCP - Australia', 'GCP - Australia'), ('GCP - Asia', 'GCP - Asia'), ('GCP - Asia-East', 'GCP - Asia-East'), ('GCP - Asia-NE', 'GCP - Asia-NE'), ('GCP - Brazil', 'GCP - Brazil'), ('Central US', 'Central US'), ('East US', 'East US'), ('East US 2', 'East US 2'), ('North Central US', 'North Central US'), ('South Central US', 'South Central US'), ('West Central US', 'West Central US'), ('West US', 'West US'), ('West US 2', 'West US 2'), ('North Europe', 'North Europe'), ('West Europe', 'West Europe'), ('East Asia', 'East Asia'), ('US East (N.Virginia)', 'US East (N.Virginia)'), ('US East (Ohio)', 'US East (Ohio)'), ('US West (Oregon)', 'US West (Oregon)'), ('US West (N. Calif.)', 'US West (N. Calif.)'), ('Africa (Cape Town)', 'Africa (Cape Town)'), ('Asia Pacific (Hong Kong)', 'Asia Pacific (Hong Kong)'), ('Asia Pacific (Mumbai)', 'Asia Pacific (Mumbai)'), ('Asia Pacific (Osaka-Local)', 'Asia Pacific (Osaka-Local)'), ('Asia Pacific (Seoul)', 'Asia Pacific (Seoul)'), ('Asia Pacific (Singapore)', 'Asia Pacific (Singapore)'), ('Asia Pacific (Sydney)', 'Asia Pacific (Sydney)'), ('Asia Pacific (Tokyo)', 'Asia Pacific (Tokyo)'), ('Canada (Central)', 'Canada (Central)'), ('Europe (Frankfurt)', 'Europe (Frankfurt)'), ('Europe (Ireland)', 'Europe (Ireland)'), ('Europe (London)', 'Europe (London)'), ('Europe (Milan)', 'Europe (Milan)'), ('Europe (Paris)', 'Europe (Paris)'), ('Europe (Stockholm)', 'Europe (Stockholm)'), ('Middle East (Bahrain)', 'Middle East (Bahrain)'), ('South America (Sao Paulo)', 'South America (Sao Paulo)'), ('AWS GovCloud (US-East)', 'AWS GovCloud (US-East)'), ('AWS GovCloud (US-West)', 'AWS GovCloud (US-West)'), ('Customer DC', 'Customer DC')], max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='multipleActiveRegions',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='requiresEUDataProtectionZoneEUDPZ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
