# Generated by Django 2.2.6 on 2020-06-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0004_auto_20200609_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteinputmodel',
            old_name='hostingModel',
            new_name='hostingProvider',
        ),
    ]
